### ISSUE TITLE
Question - SCAN_ONLY_NEW_FILES and BIG BIG folder

### ISSUE THREAD

**Issue by herewithme** [abes-esr/clamscan-docker#8]
Hello,

First of all, thank you for this inspiring open-source project.

I'm wondering about a concept in your project.
If I understand correctly, you rsync the folder to be scanned to a temporary folder within the docker container. Is this the case?

If so, does that mean that your server needs to have double the disk space? that's unmanageable with large folders, isn't it?

Thanks for the clarification!

**Comment by kerphi** [comment]
Yes, rsync is used to copy files to scan in a tmp folder. See : 
https://github.com/abes-esr/clamscan-docker/blob/main/image/do-clamscan.sh#L13-L20

So yes you need double space on your FS.

**Comment by herewithme** [comment]
Thanks for the confirmation, it's not great for our use, we'll operate differently ;)
